[package]
name = "main"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
bytes = "0.5"
env_logger = "0.7"
futures = "0.3.1"
handler = { path = "../function" }
hyper = "0.13.0"
tokio = { version = "0.2.4", features = ["macros"] }
