[package]
name = "main"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.17" }
handler = { path = "../function" }
hyper = { git = "https://github.com/hyperium/hyper", features = ["runtime"] }
tokio = { git = "https://github.com/tokio-rs/tokio" }
