[package]
name = "main"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
handler = { path = "../function" }
hyper = "0.13"
log = "0.4"
tokio = { version = "0.2", features = ["macros"] }
