version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  database:
    lang: rust-http
    handler: ./database
    image: docker.pkg.github.com/reitermarkus/serverless/database:latest
    environment:
      RUST_LOG: info
      write_debug: 'true'
      MONGO_HOST: mongo
      MONGO_DB: sensordata
    secrets:
      - mongo-root-password
      - mongo-root-username
