#!/bin/bash

set -e
set -o pipefail
set -o nounset

ip="${1}"

. build

scp "target/${TARGET}/release/sensors" pi@"${ip}:/tmp/"

ssh pi@"${ip}" < setup_timezone.sh
ssh pi@"${ip}" < setup_hostname.sh

ssh pi@"${ip}" < setup_i2c.sh
ssh pi@"${ip}" < setup_watchdog.sh

local_ip="$(hostname)"

cat <<CONFIG | ssh pi@"${ip}" sudo tee /etc/systemd/system/sensors.service
[Unit]
Description=sensors
StartLimitIntervalSec=0

[Service]
Type=simple
Environment=I2C_DEVICE=/dev/i2c-1
Environment=KAFKA_HOST=${local_ip}
Environment=KAFKA_PORT=8082
ExecStart=/usr/local/bin/sensors
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
CONFIG

ssh pi@"${ip}" sudo cp -f /tmp/sensors /usr/local/bin/sensors
ssh pi@"${ip}" sudo chmod +x /usr/local/bin/sensors
ssh pi@"${ip}" sudo mkdir -p /etc/sensors
ssh pi@"${ip}" sudo systemctl enable sensors
ssh pi@"${ip}" sudo systemctl restart sensors
