[package]
name = "handler"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
futures01 = { package = "futures", version = "0.1" }
http = "*"
openfaas = { path = "../openfaas" }
