[package]
name = "handler"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
http = "*"
mongodb = "*"
lazy_static = "*"
serde = "1"
serde_json = "1"
serde_derive = "1"
